### ISSUE TITLE
TypeError: eventEmitter.listeners is not a function. (In 'eventEmitter.listeners(EmitterMessages.SMS_RECEIVED)', 'eventEmitter.listeners' is undefined) in Expo project

### ISSUE THREAD

**Issue by e4basil** [jgkiano/react-native-android-sms-verification-api#1]
In Expo project it shows 

`TypeError: eventEmitter.listeners is not a function. (In 'eventEmitter.listeners(EmitterMessages.SMS_RECEIVED)', 'eventEmitter.listeners' is undefined)`

**Comment by jgkiano** [comment]
Hi, this library is meant for vanilla react native workflows. Expo projects are currently not supported
