### ISSUE TITLE
Auto-confirm SMS after it has been read by the app?

### ISSUE THREAD

**Issue by pke** [jgkiano/react-native-android-sms-verification-api#13]
Is it possible to auto-confirm the received SMS from the notifcation area? After successfully listening for the SMS and it being delivered to the app it remains as "new" in the OS notification centre. 
iOS has a setting to automatically delete such OTP messages once they have been auto filled (by the user by tapping on the virtual keyboard suggestion).

Maybe it already works in Android if the message is properly formatted? Currently our message has the format:
"Your code is nnnnnnn\n\n\<hash>"

Maybe when prefixing it with "<#>..." it will be removed automagically?

Couldn't find anything in the docs.

**Comment by jgkiano** [comment]
I don't think this is possible currently
