### ISSUE TITLE
  receiveVerificationSMS is giving me  undefined is not a function

### ISSUE THREAD

**Issue by mehthabux** [jgkiano/react-native-android-sms-verification-api#3]
receiveVerificationSMS is giving me  undefined is not a function.  I'm running on Hermes engine, hope that is fine. I just followed your same example

**Comment by jgkiano** [comment]
Thanks for identifying this. What react native version are you on?

**Comment by mehthabux** [comment]
hi @jgkiano  I'm currently using 0.70.6

**Comment by jgkiano** [comment]
Im experiencing the same compatibility issues with newer versions of React Native. Will work on a fix for this. Till then I'll leave this issue open.

**Comment by mehthabux** [comment]
@jgkiano thank you , hope you will fix it asap

**Comment by goblin-ihx** [comment]
> Im experiencing the same compatibility issues with newer versions of React Native. Will work on a fix for this. Till then I'll leave this issue open.

hi jgkiano, have you fixed the issue?

**Comment by mehthabux** [comment]
Hello @jgkiano have you got the chance to work on the fix ?
