### ISSUE TITLE
receiveVerificationSMS not triggering

### ISSUE THREAD

**Issue by DineshLt93** [jgkiano/react-native-android-sms-verification-api#5]
Hi, I am getting the true message for startSmsUserConsent() function.

But I can't get any error or success message for receiveVerificationSMS(). I think this is not triggered. 

Also am getting allow or deny popup but I can't get the SMS content in the below function.

`receiveVerificationSMS((error, message) => {
          if (error) {
            console.log('error',error)
          } else {
            console.log('message',message)
          }
        });`

![Screenshot from 2023-11-21 09-00-47](https://github.com/jgkiano/react-native-android-sms-verification-api/assets/62551762/a224b8b2-cf40-431a-ae6a-2f8d6b3d3ebd)

But that worked fine earlier. This issue will happen after upgrading the react native version

Older react-native version: 0.63.4
Current react-native version: 0.72.6

**Comment by jgkiano** [comment]
[Fix](https://www.npmjs.com/package/react-native-android-sms-verification-api/v/1.0.8)
