### ISSUE TITLE
getReactApplicationContext().registerReceiver ERROR API 34

### ISSUE THREAD

**Issue by bujandaluis** [jgkiano/react-native-android-sms-verification-api#6]
When uploading the version to API 34, an error is generated in the AndroidSmsVerificationApiModule.java file, in line 87 where a registerReceiver is being made and generates the error : “one of receiver_exported or receiver_not_exported should be specified”.

A solution would be to do something like this : 

“if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M && 
            getApplicationInfo().targetSdkVersion >= Build.VERSION_CODES.M) {
            // As of Android 10 (API level 29), you are required to specify which components are being exported
            registerReceiver(smsVerificationReceiver, intentFilter, Context.RECEIVER_EXPORTED, null);
        } else {
            // For versions earlier than Android 10, the use of registerReceiver is the same
            registerReceiver(smsVerificationReceiver, intentFilter);
        }”
        
 Could you make that change please.

**Comment by rmaharba** [comment]
@jgkiano I'm having the same issue, and is blocking us, there's any way you can solved it?

I think somebody in our team solved this error, can we send the PR?

**Comment by viljark** [comment]
I added a PR with the fix we are using.

**Comment by jgkiano** [comment]
`registerReceiver` has been a thorn in my side.
